sudo: required
services:
  - docker

before_install:
  - docker build
  
script:
  - 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: ""
  bucket_path: ""
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
