// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pipecoupler.proto
#ifndef GRPC_pipecoupler_2eproto__INCLUDED
#define GRPC_pipecoupler_2eproto__INCLUDED

#include "pipecoupler.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace pipecoupler {

class PipeCoupler final {
 public:
  static constexpr char const* service_full_name() {
    return "pipecoupler.PipeCoupler";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status HandleData(::grpc::ClientContext* context, const ::pipecoupler::Data& request, ::pipecoupler::Reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pipecoupler::Reply>> AsyncHandleData(::grpc::ClientContext* context, const ::pipecoupler::Data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pipecoupler::Reply>>(AsyncHandleDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pipecoupler::Reply>> PrepareAsyncHandleData(::grpc::ClientContext* context, const ::pipecoupler::Data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pipecoupler::Reply>>(PrepareAsyncHandleDataRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pipecoupler::Reply>* AsyncHandleDataRaw(::grpc::ClientContext* context, const ::pipecoupler::Data& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pipecoupler::Reply>* PrepareAsyncHandleDataRaw(::grpc::ClientContext* context, const ::pipecoupler::Data& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status HandleData(::grpc::ClientContext* context, const ::pipecoupler::Data& request, ::pipecoupler::Reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pipecoupler::Reply>> AsyncHandleData(::grpc::ClientContext* context, const ::pipecoupler::Data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pipecoupler::Reply>>(AsyncHandleDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pipecoupler::Reply>> PrepareAsyncHandleData(::grpc::ClientContext* context, const ::pipecoupler::Data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pipecoupler::Reply>>(PrepareAsyncHandleDataRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::pipecoupler::Reply>* AsyncHandleDataRaw(::grpc::ClientContext* context, const ::pipecoupler::Data& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pipecoupler::Reply>* PrepareAsyncHandleDataRaw(::grpc::ClientContext* context, const ::pipecoupler::Data& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_HandleData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status HandleData(::grpc::ServerContext* context, const ::pipecoupler::Data* request, ::pipecoupler::Reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_HandleData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_HandleData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_HandleData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleData(::grpc::ServerContext* context, const ::pipecoupler::Data* request, ::pipecoupler::Reply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandleData(::grpc::ServerContext* context, ::pipecoupler::Data* request, ::grpc::ServerAsyncResponseWriter< ::pipecoupler::Reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_HandleData<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_HandleData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_HandleData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_HandleData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleData(::grpc::ServerContext* context, const ::pipecoupler::Data* request, ::pipecoupler::Reply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_HandleData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_HandleData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::pipecoupler::Data, ::pipecoupler::Reply>(std::bind(&WithStreamedUnaryMethod_HandleData<BaseClass>::StreamedHandleData, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_HandleData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status HandleData(::grpc::ServerContext* context, const ::pipecoupler::Data* request, ::pipecoupler::Reply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHandleData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pipecoupler::Data,::pipecoupler::Reply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_HandleData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_HandleData<Service > StreamedService;
};

}  // namespace pipecoupler


#endif  // GRPC_pipecoupler_2eproto__INCLUDED
